CREATE TABLE IF NOT EXISTS `configuracion_cajas_bancos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(120) NOT NULL,
  `tipo` ENUM('CAJA','BANCO','BILLETERA','OTROS') NOT NULL DEFAULT 'BANCO',
  `entidad` VARCHAR(120) DEFAULT NULL,
  `tipo_cuenta` VARCHAR(80) DEFAULT NULL,
  `moneda` ENUM('PEN','USD') NOT NULL DEFAULT 'PEN',
  `titular` VARCHAR(150) DEFAULT NULL,
  `numero_cuenta` VARCHAR(80) DEFAULT NULL,
  `permite_cobros` TINYINT(1) NOT NULL DEFAULT 1,
  `permite_pagos` TINYINT(1) NOT NULL DEFAULT 1,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  `observaciones` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_by` BIGINT UNSIGNED DEFAULT NULL,
  `updated_by` BIGINT UNSIGNED DEFAULT NULL,
  `deleted_by` BIGINT UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cajas_bancos_codigo` (`codigo`),
  KEY `idx_cajas_bancos_tipo_estado` (`tipo`,`estado`),
  KEY `idx_cajas_bancos_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
