-- Script de referencia limpia para instalaciones nuevas del módulo de producción.
-- No reemplaza migraciones históricas: consolida estructura vigente sin bloques duplicados.

CREATE TABLE `produccion_recetas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_producto` INT(11) NOT NULL,
  `codigo` VARCHAR(30) NOT NULL,
  `version` INT(11) NOT NULL DEFAULT 1,
  `id_centro_costo` INT(11) DEFAULT NULL,
  `id_almacen_planta` INT(11) DEFAULT NULL COMMENT 'Planta predeterminada al planificar OP',
  `descripcion` VARCHAR(255) DEFAULT NULL,
  `rendimiento_base` DECIMAL(14,4) NOT NULL DEFAULT 1.0000,
  `unidad_rendimiento` VARCHAR(10) DEFAULT 'UND',
  `costo_teorico_unitario` DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  `estado` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1=Activa, 0=Inactiva',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT(11) NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` INT(11) DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL,
  `deleted_by` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_recetas_codigo` (`codigo`),
  KEY `idx_recetas_producto_estado` (`id_producto`, `estado`),
  KEY `idx_recetas_centro_costo` (`id_centro_costo`),
  KEY `idx_recetas_almacen_planta` (`id_almacen_planta`),
  KEY `idx_recetas_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_recetas_producto` FOREIGN KEY (`id_producto`) REFERENCES `items` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_recetas_centro_costo` FOREIGN KEY (`id_centro_costo`) REFERENCES `conta_centros_costo` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_recetas_almacen_planta` FOREIGN KEY (`id_almacen_planta`) REFERENCES `almacenes` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `produccion_recetas_detalle` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_receta` INT(11) NOT NULL,
  `id_insumo` INT(11) NOT NULL,
  `etapa` VARCHAR(80) DEFAULT 'General',
  `cantidad_por_unidad` DECIMAL(14,4) NOT NULL,
  `merma_porcentaje` DECIMAL(5,2) DEFAULT 0.00,
  `costo_unitario` DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT(11) NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` INT(11) DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL,
  `deleted_by` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_receta_detalle_receta` (`id_receta`),
  KEY `idx_receta_detalle_insumo` (`id_insumo`),
  KEY `idx_receta_detalle_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_receta_detalle_receta` FOREIGN KEY (`id_receta`) REFERENCES `produccion_recetas` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_receta_detalle_insumo` FOREIGN KEY (`id_insumo`) REFERENCES `items` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `produccion_ordenes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(30) NOT NULL,
  `id_receta` INT(11) NOT NULL,
  `id_producto_snapshot` INT(11) DEFAULT NULL,
  `receta_codigo_snapshot` VARCHAR(30) DEFAULT NULL,
  `receta_version_snapshot` INT(11) DEFAULT NULL,
  `costo_teorico_unitario_snapshot` DECIMAL(14,4) DEFAULT NULL,
  `costo_teorico_total_snapshot` DECIMAL(14,4) DEFAULT NULL,
  `costo_real_unitario` DECIMAL(14,4) DEFAULT NULL,
  `costo_real_total` DECIMAL(14,4) DEFAULT NULL,
  `total_md_real` DECIMAL(14,4) DEFAULT NULL,
  `total_mod_real` DECIMAL(14,4) DEFAULT NULL,
  `total_cif_real` DECIMAL(14,4) DEFAULT NULL,
  `costo_unitario_real` DECIMAL(14,4) DEFAULT NULL,
  `id_almacen_planta` INT(11) DEFAULT NULL,
  `cantidad_planificada` DECIMAL(14,4) NOT NULL,
  `cantidad_producida` DECIMAL(14,4) DEFAULT 0.0000,
  `estado` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0=Borrador, 1=En Proceso, 2=Ejecutada, 9=Anulada',
  `fecha_programada` DATE DEFAULT NULL,
  `fecha_inicio` DATETIME DEFAULT NULL,
  `fecha_fin` DATETIME DEFAULT NULL,
  `observaciones` TEXT DEFAULT NULL,
  `justificacion_ajuste` TEXT DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT(11) NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` INT(11) DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL,
  `deleted_by` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_op_codigo` (`codigo`),
  KEY `idx_op_receta` (`id_receta`),
  KEY `idx_op_producto_snapshot` (`id_producto_snapshot`),
  KEY `idx_op_almacen_planta` (`id_almacen_planta`),
  KEY `idx_op_fecha_estado_costos` (`fecha_programada`, `estado`, `id_receta`),
  KEY `idx_op_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_op_receta` FOREIGN KEY (`id_receta`) REFERENCES `produccion_recetas` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_op_producto_snapshot` FOREIGN KEY (`id_producto_snapshot`) REFERENCES `items` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_op_almacen_planta` FOREIGN KEY (`id_almacen_planta`) REFERENCES `almacenes` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `produccion_consumos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_orden_produccion` INT(11) NOT NULL,
  `id_item` INT(11) NOT NULL,
  `id_almacen` INT(11) DEFAULT NULL,
  `id_lote` INT(11) DEFAULT NULL,
  `cantidad` DECIMAL(14,4) NOT NULL,
  `costo_unitario` DECIMAL(14,4) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT(11) NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` INT(11) DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL,
  `deleted_by` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_cons_op` (`id_orden_produccion`),
  KEY `idx_cons_item` (`id_item`),
  KEY `idx_cons_created_item` (`created_at`, `id_item`),
  KEY `idx_cons_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_cons_op` FOREIGN KEY (`id_orden_produccion`) REFERENCES `produccion_ordenes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_cons_item` FOREIGN KEY (`id_item`) REFERENCES `items` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_cons_almacen` FOREIGN KEY (`id_almacen`) REFERENCES `almacenes` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_cons_lote` FOREIGN KEY (`id_lote`) REFERENCES `inventario_lotes` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `produccion_ingresos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_orden_produccion` INT(11) NOT NULL,
  `id_item` INT(11) NOT NULL,
  `id_almacen` INT(11) DEFAULT NULL,
  `lote` VARCHAR(60) DEFAULT NULL,
  `fecha_vencimiento` DATE DEFAULT NULL,
  `cantidad` DECIMAL(14,4) NOT NULL,
  `costo_unitario_calculado` DECIMAL(14,4) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT(11) NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `updated_by` INT(11) DEFAULT NULL,
  `deleted_at` DATETIME DEFAULT NULL,
  `deleted_by` INT(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ing_op` (`id_orden_produccion`),
  KEY `idx_ing_item` (`id_item`),
  KEY `idx_ing_created_item` (`created_at`, `id_item`),
  KEY `idx_ing_deleted_at` (`deleted_at`),
  CONSTRAINT `fk_ing_op` FOREIGN KEY (`id_orden_produccion`) REFERENCES `produccion_ordenes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_ing_item` FOREIGN KEY (`id_item`) REFERENCES `items` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_ing_almacen` FOREIGN KEY (`id_almacen`) REFERENCES `almacenes` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `produccion_ordenes_mod` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_orden` INT(11) NOT NULL,
  `id_empleado` INT(11) NOT NULL,
  `horas_reales` DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  `costo_hora_real` DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  `costo_total_mod` DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_prod_mod_orden` (`id_orden`),
  KEY `idx_prod_mod_empleado` (`id_empleado`),
  CONSTRAINT `fk_prod_mod_orden` FOREIGN KEY (`id_orden`) REFERENCES `produccion_ordenes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_prod_mod_empleado` FOREIGN KEY (`id_empleado`) REFERENCES `terceros` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `produccion_ordenes_cif` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_orden` INT(11) NOT NULL,
  `concepto` VARCHAR(120) NOT NULL,
  `id_activo` INT(11) DEFAULT NULL,
  `base_distribucion` VARCHAR(80) DEFAULT NULL,
  `costo_aplicado` DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_prod_cif_orden` (`id_orden`),
  KEY `idx_prod_cif_activo` (`id_activo`),
  CONSTRAINT `fk_prod_cif_orden` FOREIGN KEY (`id_orden`) REFERENCES `produccion_ordenes` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_prod_cif_activo` FOREIGN KEY (`id_activo`) REFERENCES `activos_fijos` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
